In [10]:
import torch
q_length_max = 50
k_length_max = 25
q_length_list = [1, 2, 3, 4, 5]
k_length_list = [2, 3, 4, -1, -1]
memory_mask_init = [[float('-inf') for _ in range(k_length_max)] for _ in range(q_length_max)]
for q_index, v_index in zip(q_length_list, k_length_list):
    memory_mask_init[q_index][v_index] = float(0.0)
memory_mask = [memory_mask_init for _ in range(8)]
memory_mask = torch.FloatTensor(memory_mask)
print(memory_mask)

tensor([[[-inf, -inf, -inf,  ..., -inf, -inf, -inf],
         [-inf, -inf, 0.,  ..., -inf, -inf, -inf],
         [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
         ...,
         [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
         [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
         [-inf, -inf, -inf,  ..., -inf, -inf, -inf]],

        [[-inf, -inf, -inf,  ..., -inf, -inf, -inf],
         [-inf, -inf, 0.,  ..., -inf, -inf, -inf],
         [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
         ...,
         [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
         [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
         [-inf, -inf, -inf,  ..., -inf, -inf, -inf]],

        [[-inf, -inf, -inf,  ..., -inf, -inf, -inf],
         [-inf, -inf, 0.,  ..., -inf, -inf, -inf],
         [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
         ...,
         [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
         [-inf, -inf, -inf,  ..., -inf, -inf, -inf],
         [-inf, -inf, -inf,  ..., -inf, -inf, -inf]],

    

In [3]:
print(22//11)

2


In [21]:
import random
import numpy
num_heads=8
def get_triple_index(length1, length2, k=3):
    double_index = [[], []]
    
    length1_randoms = random.sample(list(range(0, length1 - 1)), k)
    length2_randoms = random.sample(list(range(0, length2 - 1)), k)
    for length1_random, length2_random in zip(length1_randoms, length2_randoms):
        double_index[0].append(length1_random)
        double_index[1].append(length2_random)
    double_index[0].append(length1_random - 1)
    double_index[1].append(length2_random - 1)
    return double_index

def get_memory_mask(q_length_list, k_length_list, q_length_max, k_length_max):
    memory_mask_init = [[float (0.0) for _ in range (k_length_max)] for _ in range (q_length_max)]
    for q_index, v_index in zip (q_length_list, k_length_list):
        for k_ in range (k_length_max):
            if k_ > v_index:
                memory_mask_init[q_index][k_] = float('-inf')
        # memory_mask_init[q_index][v_index] = float(0.0)
    memory_mask = [memory_mask_init for _ in range(num_heads)]
    return memory_mask

anchor_near_double = get_triple_index(5, 6)
anchor_far_double = get_triple_index(5, 7)

In [22]:
print(numpy.array(get_memory_mask(anchor_near_double[0], anchor_near_double[1], 8,9)))

[[[-inf -inf -inf -inf -inf -inf -inf -inf -inf]
  [  0. -inf -inf -inf -inf -inf -inf -inf -inf]
  [  0.   0.   0.   0.   0. -inf -inf -inf -inf]
  [  0.   0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.   0.]]

 [[-inf -inf -inf -inf -inf -inf -inf -inf -inf]
  [  0. -inf -inf -inf -inf -inf -inf -inf -inf]
  [  0.   0.   0.   0.   0. -inf -inf -inf -inf]
  [  0.   0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0.   0.   0.   0.   0.   0.   0.]]

 [[-inf -inf -inf -inf -inf -inf -inf -inf -inf]
  [  0. -inf -inf -inf -inf -inf -inf -inf -inf]
  [  0.   0.   0.   0.   0. -inf -inf -inf -inf]
  [  0.   0.   0.   0.   0.   0.   0.   0.   0.]
  [  0.   0.   0